// 30 motores - EXACTAMENTE los listados en el documento Word de GOGEN-TAYLOR
// No se han añadido ni inventado motores.

export const engines = [
  // ── FAMILIA: REFRIGERADOS POR AIRE ──────────────────────────────────
  {
    id: 'serie-511',
    name: 'Serie 511',
    altNames: ['F2L 511', 'F3L 511', '511'],
    familyId: 'air-cooled',
    generation: 'classic',
    aspiration: 'natural',
    cylinders: { count: 3, configuration: 'L' },
    displacement: '2.2 L',
    power: '20–34 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['agrícola', 'generación', 'industrial'],
    description:
      'Motor Deutz clásico refrigerado por aire de la serie 511. Uno de los motores industriales más icónicos de Deutz, de gran durabilidad y mantenimiento sencillo. Muy extendido en maquinaria agrícola y grupos electrógenos de las décadas de 1970 y 1980.',
  },
  {
    id: 'serie-413',
    name: 'Serie 413 / BF 413',
    altNames: ['F8L 413', 'F10L 413', 'BF8L 413', 'BF12L 413'],
    familyId: 'air-cooled',
    generation: 'classic',
    aspiration: 'turbo',
    cylinders: { count: 8, configuration: 'V' },
    displacement: '11.3–15.8 L',
    power: '190–450 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['construcción', 'generación', 'industrial', 'marino'],
    description:
      'Motor Deutz de alta potencia refrigerado por aire, disponible en versión atmosférica y turboalimentada (BF). Configuración en V de 8, 10 o 12 cilindros. Muy utilizado en camiones de construcción pesada y grupos electrógenos de gran tamaño.',
  },
  {
    id: 'serie-513',
    name: 'Serie 513 / BF 513',
    altNames: ['F8L 513', 'F10L 513', 'BF8L 513', 'BF12L 513'],
    familyId: 'air-cooled',
    generation: 'classic',
    aspiration: 'turbo',
    cylinders: { count: 8, configuration: 'V' },
    displacement: '12.7–19.1 L',
    power: '220–530 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['construcción', 'generación', 'industrial'],
    description:
      'Evolución de la serie 413 con mayor cilindrada y potencia. Mantiene la configuración en V y la refrigeración por aire. Versiones turboalimentadas (BF) para las aplicaciones más exigentes.',
  },
  {
    id: 'serie-912',
    name: 'Serie 912',
    altNames: ['F3L 912', 'F4L 912', 'F6L 912'],
    familyId: 'air-cooled',
    generation: 'classic',
    aspiration: 'natural',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '2.8–5.6 L',
    power: '25–75 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['agrícola', 'construcción', 'generación'],
    description:
      'Una de las series más populares de Deutz. Motor atmosférico refrigerado por aire en configuraciones de 3, 4 y 6 cilindros. Referencia en maquinaria agrícola y de construcción ligera.',
  },
  {
    id: 'serie-913',
    name: 'Serie 913',
    altNames: ['F3L 913', 'F4L 913', 'F6L 913'],
    familyId: 'air-cooled',
    generation: 'classic',
    aspiration: 'natural',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '3.2–6.1 L',
    power: '35–85 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['agrícola', 'construcción', 'industrial'],
    description:
      'Evolución de la serie 912 con mayor cilindrada y prestaciones. Mantiene la refrigeración por aire característica de Deutz. Disponible en 3, 4 y 6 cilindros.',
  },
  {
    id: 'bf6l-913-bf4l-913',
    name: 'Serie BF6L 913 y BF4L 913',
    altNames: ['BF4L 913', 'BF6L 913', 'BF913'],
    familyId: 'air-cooled',
    generation: 'classic',
    aspiration: 'turbo',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '4.1–6.1 L',
    power: '60–130 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['construcción', 'industrial', 'generación'],
    description:
      'Versiones turboalimentadas de la serie 913 en configuraciones de 4 y 6 cilindros. La turboalimentación permite un incremento significativo de potencia manteniendo la fiabilidad de la gama.',
  },
  {
    id: 'serie-914',
    name: 'Serie 914',
    altNames: ['F3L 914', 'F4L 914', 'F6L 914'],
    familyId: 'air-cooled',
    generation: 'classic',
    aspiration: 'natural',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '3.8–7.1 L',
    power: '35–100 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['agrícola', 'construcción', 'industrial'],
    description:
      'Última gran serie refrigerada por aire de Deutz, con mayor desplazamiento por cilindro que las series 912/913. Configuraciones de 3, 4 y 6 cilindros.',
  },
  {
    id: 'bf6l-914-bf4l-914',
    name: 'Serie BF6L 914 y BF4L 914',
    altNames: ['BF4L 914', 'BF6L 914', 'BF914'],
    familyId: 'air-cooled',
    generation: 'classic',
    aspiration: 'turbo',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '4.8–7.1 L',
    power: '75–160 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['construcción', 'industrial'],
    description:
      'Versiones turboalimentadas de la serie 914 en 4 y 6 cilindros. Cierre de la gama refrigerada por aire de Deutz antes de la transición a refrigeración por líquido.',
  },

  // ── FAMILIA: REFRIGERADOS POR AGUA / ACEITE ────────────────────────
  {
    id: 'serie-1011',
    name: 'Serie 1011 / 1011F',
    altNames: ['1011', '1011F', 'F2M 1011', 'F3M 1011', 'F4M 1011'],
    familyId: 'water-oil-cooled',
    generation: 'transitional',
    aspiration: 'natural',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '1.5–2.3 L',
    power: '15–45 kW',
    fuelSystem: 'Mecánica rotativa',
    emissionStage: null,
    applications: ['industrial', 'agrícola', 'construcción'],
    description:
      'Primera serie Deutz refrigerada por aceite. Compacta y ligera, muy utilizada en maquinaria compacta, carretillas elevadoras y pequeños grupos electrógenos. Variante 1011F con refrigeración mejorada.',
  },
  {
    id: 'serie-1012',
    name: 'Serie 1012 / 1012C',
    altNames: ['1012', '1012C', 'BF4M 1012', 'BF6M 1012'],
    familyId: 'water-oil-cooled',
    generation: 'transitional',
    aspiration: 'turbo',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '4.8–7.2 L',
    power: '75–220 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['construcción', 'agrícola', 'industrial'],
    description:
      'Serie refrigerada por aceite con versiones turboalimentadas e intercooler. La variante 1012C incorpora mejoras específicas para aplicaciones continuas. Configuraciones de 4 y 6 cilindros.',
  },
  {
    id: 'serie-1013',
    name: 'Serie 1013',
    altNames: ['1013', 'BF4M 1013', 'BF6M 1013'],
    familyId: 'water-oil-cooled',
    generation: 'transitional',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '4.8–7.1 L',
    power: '85–240 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['construcción', 'agrícola', 'industrial'],
    description:
      'Evolución de la serie 1012 con mayor rendimiento. Versiones turbo e intercooler disponibles para las aplicaciones más exigentes. Configuraciones de 4 y 6 cilindros.',
  },
  {
    id: 'serie-2011',
    name: 'Serie 2011',
    altNames: ['2011', 'F2L 2011', 'F3L 2011', 'F4L 2011'],
    familyId: 'water-oil-cooled',
    generation: 'transitional',
    aspiration: 'natural',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '2.0–3.1 L',
    power: '20–55 kW',
    fuelSystem: 'Mecánica rotativa',
    emissionStage: null,
    applications: ['industrial', 'agrícola', 'generación'],
    description:
      'Sucesor directo de la serie 1011. Motor refrigerado por aceite compacto y fiable. Configuraciones de 2, 3 y 4 cilindros, muy utilizado en carretillas, plataformas elevadoras y maquinaria compacta.',
  },
  {
    id: 'serie-2012',
    name: 'Serie 2012',
    altNames: ['2012', 'BF4M 2012', 'BF6M 2012'],
    familyId: 'water-oil-cooled',
    generation: 'transitional',
    aspiration: 'turbo',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '4.8–7.2 L',
    power: '90–240 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['construcción', 'agrícola', 'industrial'],
    description:
      'Evolución de la serie 1012 con mejoras en rendimiento y fiabilidad. Versiones turboalimentadas disponibles en 4 y 6 cilindros.',
  },
  {
    id: 'serie-1015',
    name: 'Serie 1015',
    altNames: ['1015', 'BF6M 1015', 'BF8M 1015'],
    familyId: 'water-oil-cooled',
    generation: 'transitional',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 8, configuration: 'V' },
    displacement: '11.9–15.9 L',
    power: '240–550 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: null,
    applications: ['construcción', 'generación', 'industrial'],
    description:
      'Motor de alta potencia en configuración V8 y V10, refrigerado por líquido. Pensado para maquinaria de gran tonelaje y grupos electrógenos de gran potencia.',
  },
  {
    id: 'serie-2013',
    name: 'Serie 2013 / 2013M',
    altNames: ['2013', '2013M', 'BF4M 2013', 'BF6M 2013'],
    familyId: 'water-oil-cooled',
    generation: 'transitional',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '4.8–7.1 L',
    power: '110–260 kW',
    fuelSystem: 'Mecánica en línea',
    emissionStage: 'III',
    applications: ['construcción', 'agrícola', 'industrial', 'marino'],
    description:
      'Evolución de la serie 1013 con cumplimiento de emisiones Stage III. La variante 2013M está optimizada para uso marino. Configuraciones de 4 y 6 cilindros turboalimentados.',
  },

  // ── FAMILIA: TCD ELECTRÓNICOS ───────────────────────────────────────
  {
    id: 'tcd-2012',
    name: 'Serie TCD 2012',
    altNames: ['TCD 2012', 'TCD2012'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '4.0–4.8 L',
    power: '90–170 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'IIIB',
    applications: ['construcción', 'agrícola', 'industrial'],
    description:
      'Primer TCD electrónico con inyección Common Rail. Gestión EMR 2/3, cumplimiento Stage IIIB. Motor referencia en maquinaria pesada y agrícola moderna.',
  },
  {
    id: 'tcd-2013',
    name: 'Serie TCD 2013',
    altNames: ['TCD 2013', 'TCD2013'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '6.1–7.1 L',
    power: '135–300 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'IIIB',
    applications: ['construcción', 'agrícola', 'generación', 'marino'],
    description:
      'Gama electrónica de 6 cilindros con inyección Common Rail, gestión EMR y cumplimiento Stage IIIB. Amplio uso en maquinaria de construcción y grupos electrógenos.',
  },
  {
    id: 'tcd-2015',
    name: 'Serie TCD 2015',
    altNames: ['TCD 2015', 'TCD2015'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 8, configuration: 'V' },
    displacement: '11.9–16.0 L',
    power: '325–620 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'IIIA',
    applications: ['construcción', 'generación', 'industrial'],
    description:
      'Motor electrónico de gran potencia en configuración V6 y V8. Aplicaciones de gran tonelaje, grupos electrógenos industriales y maquinaria minera.',
  },
  {
    id: 'tcd-1013',
    name: 'Serie TCD 1013',
    altNames: ['TCD 1013', 'TCD1013'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '6.1–7.1 L',
    power: '130–240 kW',
    fuelSystem: 'Unit Pump',
    emissionStage: 'IIIA',
    applications: ['construcción', 'agrícola', 'industrial'],
    description:
      'Variante electrónica del 1013 con inyección Unit Pump. Paso intermedio hacia el Common Rail. Cumplimiento Stage IIIA.',
  },
  {
    id: 'tcd-2-9-l4',
    name: 'Serie TCD 2.9 L4',
    altNames: ['TCD 2.9', 'TCD 2.9 L4', 'TCD2.9'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '2.9 L',
    power: '36–75 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['agrícola', 'construcción', 'industrial'],
    description:
      'Motor compacto electrónico con gestión EMR4 y cumplimiento Stage V. Muy utilizado en maquinaria compacta, carretillas elevadoras y plataformas.',
  },
  {
    id: 'tcd-3-6-l4',
    name: 'Serie TCD 3.6 L4',
    altNames: ['TCD 3.6', 'TCD 3.6 L4', 'TCD3.6'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '3.6 L',
    power: '55–100 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['agrícola', 'construcción'],
    description:
      'Motor electrónico de 4 cilindros con inyección Common Rail y cumplimiento Stage V. Gestión EMR4. Muy presente en maquinaria agrícola y de construcción moderna.',
  },
  {
    id: 'tcd-4-1-l4',
    name: 'Serie TCD 4.1 L4',
    altNames: ['TCD 4.1', 'TCD 4.1 L4', 'TCD4.1'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '4.1 L',
    power: '75–155 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['construcción', 'agrícola', 'industrial'],
    description:
      'Motor electrónico de 4 cilindros de alta cilindrada. Mayor par y potencia que el TCD 3.6 manteniendo el mismo bloque compacto. Stage V y EMR4.',
  },
  {
    id: 'tcd-6-1-l6',
    name: 'Serie TCD 6.1 L6',
    altNames: ['TCD 6.1', 'TCD 6.1 L6', 'TCD6.1'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '6.1 L',
    power: '155–250 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['construcción', 'agrícola', 'generación'],
    description:
      'Motor de 6 cilindros en línea con Common Rail y gestión electrónica EMR4. Stage V. Referencia en maquinaria pesada agrícola y construcción.',
  },
  {
    id: 'tcd-7-8-l6',
    name: 'Serie TCD 7.8 L6',
    altNames: ['TCD 7.8', 'TCD 7.8 L6', 'TCD7.8'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '7.8 L',
    power: '210–300 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['construcción', 'agrícola', 'generación', 'marino'],
    description:
      'Motor de alto par de 6 cilindros y 7.8 litros. Aplicaciones de gran exigencia: maquinaria forestal, agrícola pesada y grupos electrógenos.',
  },
  {
    id: 'tcd-12-16-v6v8',
    name: 'Serie TCD 12.0 / 16.0 V6/V8',
    altNames: ['TCD 12.0', 'TCD 16.0', 'TCD 12.0 V6', 'TCD 16.0 V8'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 8, configuration: 'V' },
    displacement: '12.0–16.0 L',
    power: '390–620 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['construcción', 'generación', 'industrial'],
    description:
      'Gama electrónica de gran potencia en V6 (12.0 L) y V8 (16.0 L). Stage V, EMR4. Aplicaciones de minería, grupos electrógenos industriales y maquinaria pesada.',
  },
  {
    id: 'tcd-2-2',
    name: 'Serie TCD 2.2',
    altNames: ['TCD 2.2', 'TCD2.2'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 3, configuration: 'L' },
    displacement: '2.2 L',
    power: '35–55 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['construcción', 'agrícola', 'industrial'],
    description:
      'Motor compacto de 3 cilindros con Common Rail y Stage V. El más pequeño de la gama TCD electrónica. Ideal para maquinaria compacta y equipos ligeros.',
  },
  {
    id: 'tcd-3-9-4-0',
    name: 'Serie TCD 3.9 / 4.0',
    altNames: ['TCD 3.9', 'TCD 4.0', 'TCD3.9', 'TCD4.0'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '3.9–4.0 L',
    power: '85–170 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['agrícola', 'construcción', 'generación'],
    description:
      'Motor electrónico de 4 cilindros en variantes 3.9 y 4.0 litros. Gestión EMR4, Stage V. Enfocado a aplicaciones agrícolas y de construcción de gama media.',
  },
  {
    id: 'tcd-5-2',
    name: 'Serie TCD 5.2',
    altNames: ['TCD 5.2', 'TCD5.2'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 4, configuration: 'L' },
    displacement: '5.2 L',
    power: '120–180 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['construcción', 'agrícola', 'generación'],
    description:
      'Motor electrónico de 4 cilindros y alta cilindrada (5.2 L). Combina compacidad de 4 cilindros con el par de un 6 cilindros. Stage V, EMR4.',
  },
  {
    id: 'tcd-7-7',
    name: 'Serie TCD 7.7',
    altNames: ['TCD 7.7', 'TCD7.7'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 6, configuration: 'L' },
    displacement: '7.7 L',
    power: '200–290 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['construcción', 'agrícola', 'generación', 'marino'],
    description:
      'Motor de 6 cilindros y 7.7 litros, gestión electrónica EMR4 y Stage V. Alta durabilidad para aplicaciones continuas e intensivas.',
  },
  {
    id: 'tcd-12-18',
    name: 'Serie TCD 12.0 / 18.0',
    altNames: ['TCD 12.0', 'TCD 18.0', 'TCD12.0', 'TCD18.0'],
    familyId: 'tcd-electronic',
    generation: 'electronic',
    aspiration: 'turbo-intercooler',
    cylinders: { count: 8, configuration: 'V' },
    displacement: '12.0–18.0 L',
    power: '400–700 kW',
    fuelSystem: 'Common Rail',
    emissionStage: 'V',
    applications: ['construcción', 'generación', 'industrial'],
    description:
      'Gama más alta de Deutz en configuración V. Versiones de 12.0 y 18.0 litros para aplicaciones de máxima potencia: minería, grupos electrógenos de gran tamaño e industria pesada.',
  },
];

export const getEngine = (id) => engines.find((e) => e.id === id);

export const getEnginesByFamily = (familyId) =>
  engines.filter((e) => e.familyId === familyId);
